# Introduction to Python and Jupyter Lab

Acknowledgements: [Florian Lemmerich](http://lemmerich.net/florian/), for the original version of this Notebook.

## Setting up your working environment

Use the rocket symbol in the top-right corner to move this notebook to Binder or Google Colab (allows to save your progress, but needs a Google account).

**Alternatively**, if you absolutely want to, you can set up a Python environment with Conda locally. Students usually encounter a couple of roadblocks here so it takes long. Help for this kind of setup is only given in the first exercise session.

1) Install [Anaconda](https://www.anaconda.com/products/distribution) (or [miniconda](https://docs.conda.io/en/latest/miniconda.html) or [mamba](https://mamba.readthedocs.io/en/latest/installation/mamba-installation.html) if you know what you are doing)
2) Open the directory where this file is in your terminal.
3) Install dependencies (python, jupyterlab, python packages) into a new conda environment with `conda env create -f environment.yml`.
4) Start Jupyter Lab from the terminal with `jupyter lab`.

## Variables and data types

Execute the cell with `Shift+Enter` or `Ctrl+Enter`:

Click on the left of a cell to get into the "blue" mode then you can press:
* a -> new cell above the current cell
* b -> new cell below the current cell
* x -> delete the current cell

Click within a cell to get into the "green" mode (edit mode). Now you can write code here.


In [1]:
# print statements give out information
print ("Hello")
print ("World")

Hello
World


In [2]:
x = "Hello!"
print(x)

y = "Hello"
x = " World"
print (y + x)

x = 5
y = 2
print (x + y)

Hello!
Hello World
7


In [3]:
x

5

In [4]:
print (4+5)
print (x == 10)

9
False


In [5]:
x = "Hello"
y = "World"
print (x + y)

HelloWorld


In [6]:
# Python is dynamically typed, types can change:
x = "hello"
print (x)
x = 5
print (x)

hello
5


In [7]:
# main data types:
x = 5
print(type(x))

x = 5.0
print(type(x))

x = "5"
print(type(x))

x = True
print(type(x))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>


In [8]:
# Python is strongly typed
x = "5"
y = 2
x+y

TypeError: can only concatenate str (not "int") to str

In [9]:
type(x)

str

In [10]:
x = "5"
y = "4"
int(x)+int(y)

9

## Data structures

### Lists

In [11]:
# creating an empty list
l = []

In [12]:
# adding elements to the list
l.append (2)
l.append (5)
l.append (10)
l

[2, 5, 10]

In [13]:
l[1]

5

In [14]:
# accessing the last element
l[-1]


10

In [15]:
# accessing a slice (end index is excluded)
l[:-1]

[2, 5]

In [16]:
#setting an element 
l[2] = 7.3
l

[2, 5, 7.3]

In [17]:
#the length of a list:
len (l)

3

In [18]:
# We can also directly specify lists:
# a list with integer objects
list_2 = [3,5,7,9]

# a list of strings
list_3 = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']

# a list of mixed types
list_4 = [2, 5, "Elephant", 6, 8.2, True]

In [19]:
# we can also do lists of lists!
lol = [[1,2,3], ["a","b","c"], [1.2,2.3,4.5,6.7,8.9]]

In [20]:
#the length of a list:
len(lol)

3

### Tuples

Tuples are just the same as lists, but they are *immutable*.

In [21]:
t = (1,2,3)

In [22]:
t[1]

2

In [23]:
t[1] = 5

TypeError: 'tuple' object does not support item assignment

### Sets

Sets are similar collections, but have no order and can contain each element only once

In [24]:
s = set()
s.add(50)
s.add(20)
s.add(10)
s.add(20)
s

{10, 20, 50}

In [25]:
l = [2,3,4,5,6,2,3,4,5,2]

In [26]:
s = set()
for x in l:
    s.add(x)
s

{2, 3, 4, 5, 6}

In [27]:
list (set(l))

[2, 3, 4, 5, 6]

### Dictionaries

 Python’s built-in mapping type. They map keys, which can be any immutable (unchangable) type, to values, which can be any type.

In [28]:
d = dict()
d = {}

In [29]:
presidents_first_inauguration = {}
presidents_first_inauguration['Biden'] = 2021
presidents_first_inauguration['Trump'] = 2017
presidents_first_inauguration['Obama'] = 2009
presidents_first_inauguration['Bush'] = 2001
print(presidents_first_inauguration)

{'Biden': 2021, 'Trump': 2017, 'Obama': 2009, 'Bush': 2001}


In [30]:
# or, shorter:
presidents_first_inauguration = {'Biden': 2021,
                            'Trump': 2017, 
                            'Obama': 2009, 
                            'Bush': 2001}

In [31]:
presidents_first_inauguration ["Trump"]

2017

In [32]:
print (presidents_first_inauguration.keys())
print (presidents_first_inauguration.values())

dict_keys(['Biden', 'Trump', 'Obama', 'Bush'])
dict_values([2021, 2017, 2009, 2001])


In [33]:
len (presidents_first_inauguration)

4

## Control statements

control flow in Python noticeable does not use ANY (,),[,],{,},...
Instead *indendation* determines what belongs to block of commands

### If-elif-else

In [34]:
x = 10
if x > 5:
    print ('This is a big number!')


This is a big number!


In [35]:
#Note the difference
x = 0
y = 0
if x > 5:
    x = x + 1
    y = y + 1
print (y)

x = 0
y = 0
if x > 5:
    x = x + 1
y = y + 1
print (y)

0
1


In [36]:
x = 15
if x > 20:
    print ('This is a very big number!')
elif x > 10:
    print ('This is a big number!')
else:
    print ('this is a small number!')

This is a big number!


In [37]:
x = 10
command = 'increment'
if command =='increment':
    x = x + 1
print (x)

11


### Loops

In [38]:
first_names = ['John', 'Paul', 'George', 'Ringo']
for name in first_names:
    print("Hello " + name + "!")

Hello John!
Hello Paul!
Hello George!
Hello Ringo!


Contrary to many other programming languages there is no built-in for... counting loop.
However, you can use the range function:


In [39]:
list(range(10,20,3))

[10, 13, 16, 19]

In [40]:
for i in range(10):
    print (i)

0
1
2
3
4
5
6
7
8
9


In [41]:
# enumerate is a useful convenience function.
# Note how pairs (index, name) are split up into separate variables.
for index, name in enumerate(first_names):
    print("Name "+ str(index) + ": " + name)

Name 0: John
Name 1: Paul
Name 2: George
Name 3: Ringo


In [42]:
# We can loop over any iterable, e.g., also on strings.
x = "example"
for letter in x:
    print (letter)

e
x
a
m
p
l
e


In [43]:
# As a simple example, lets create a dictionary, which maps each string in a list to its length:
name_lengths = {}
for name in first_names:
    name_lengths[name] = len(name)
name_lengths

{'John': 4, 'Paul': 4, 'George': 6, 'Ringo': 5}

In [44]:
# while loops function very similar to many popular languages:
x = 1
while True:
    x = x * 2
    if x >= 100:
        break
    print(x)
    

2
4
8
16
32
64


## Functions

Defining your own functions is easy:

In [45]:
l = [1,2,3,4,5324,2,5,2,3,65,2]
len(l)

11

In [46]:
def print_all_names(names):
    for x in names:
        print (x)

In [47]:
print_all_names(l)

1
2
3
4
5324
2
5
2
3
65
2


In [48]:
def increment_function(x):
    x = x + 1
    return x

In [49]:
increment_function(5)

6

In [50]:
# You can call a function using its parameters names
def my_division(nominator,denominator):
    return nominator / denominator

print(my_division(12,4))
# you can call function parameters by name!
print(my_division(denominator=4, nominator=16))

3.0
4.0


In [51]:
# You can also specify default parameters for a function
def my_division(nominator,denominator = 2):
    return nominator / denominator

print (my_division(12,3))

4.0


In [52]:
# n
y = 5
x = 2
def increment_value(x):
    y = x + 1
    return y
increment_value(3)
y

5

## Imports

Python has a lot of built-in packages you can use, or you can download and install more packages from the internet.
Using such packages is easy:

In [53]:
import statistics

statistics.mean([3,5,7,9])

6

In [54]:
# you can also import just single functions from a package
from math import log
log(2.71 * 2.72)

1.9975805151995156

## List Comprehension

In [55]:
my_list = [2,6,5,4,66,9,100,55,4,6,4,2]

l2 = [2*x for x in my_list]
l2

[4, 12, 10, 8, 132, 18, 200, 110, 8, 12, 8, 4]

In [56]:
l3 = []
for x in my_list:
    l3.append(2*x)
l3

[4, 12, 10, 8, 132, 18, 200, 110, 8, 12, 8, 4]

In [57]:
my_list = [2,6,5,4,66,9,100,55,4,6,4,2]

new_list = [len(str(x)) for x in my_list if x > 20]
new_list

[2, 3, 2]

In [58]:
nl = []
for x in my_list:
    if x > 20:
        nl.append(x*2)
nl

[132, 200, 110]

## numpy


In [59]:
import numpy as np

x = np.array([1,2,3])
x * 4

array([ 4,  8, 12])

In [60]:
m = np.array([[1,2,3],[4,5,6],[7,8,9]])
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
m * 2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [62]:
m.dot(x)

array([14, 32, 50])

In [63]:
m[1,2]

np.int64(6)